osx_image: xcode7.2
language: objective-c

env:
  global:
    - LANG=en_US.UTF-8

branches:
  only:
    - master
    - /.+-stable$/

install: rake app:prerequisites --quiet
script: rake bundle:test --quiet
